name: Upload nseazy to PyPI

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'version tag to deploy'
        required: true
        type: string

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        ref:  ${{ github.event.inputs.tag }}

    - name: Display Coded Version 
      run: egrep 'version_info .*=' nseazy/_version.py

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build 
      run: |
        python setup.py sdist bdist_wheel
        ls -l dist/*

    - name: Publish distribution to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      run: twine upload dist/*
